name: Reusable Heavy Workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Maven Build
      run: mvn -B test --file ./${{ inputs.project }}/pom.xml -Dgroups=UnitTests

  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven Build
        run: mvn -B test --file ./${{ inputs.project }}/pom.xml -Dgroups=IntegrationTests

  package:
    needs: build_unit_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy -Dmaven.wagon.http.pool=false --file ./${{ inputs.project }}/pom.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
