name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  build_unit_test_and_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Maven Build
      run: mvn -B package --file ./${{ inputs.project }}/pom.xml -Dtest=UnitTests -DfailIfNoTests=false
    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode deploy -Dmaven.wagon.http.pool=false --file ./${{ inputs.project }}/pom.xml -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
